query propertyPage($id: ID!) {
  property(id: $id) {
    id

    internalID
    deal
    type
    subType
    commercialUsage

    fromDeveloper

    inComplex
    complex {
      id
      title
    }
    complexHouse {
      id
      title
    }

    inVillage
    village {
      id
      title
    }

    isHot

    title
    description
    address
    lat
    lon
    cadastrNumber
    seoText
    youtubeLink
    tourLink

    documents {
      id
      url
      title
    }
    images {
      id
      url
      title
    }

    isDeleted
    refreshDate

    status

    price
    pricePerMeter
    pricePerAr

    isReady
    readinessYear
    readinessQuarter

    inCity
    cityDistance
    region
    subRegion

    source

    rooms
    area
    landArea
    livingArea
    kitchenArea
    toiletType
    rehabType
    floor
    floors
    ceilingHeight

    internalInfo

    comissionPercent
    comissionAmount

    createdAt
    updatedAt
  }
}
