export { default as AgentColumn } from "./AgentColumn.vue";
export { default as ContactsColumn } from "./ContactsColumn.vue";
export { default as ContactColumn } from "./ContactColumn.vue";
export { default as DateColumn } from "./DateColumn.vue";
export { default as InternalNumberColumn } from "./InternalNumberColumn.vue";
export { default as SourceColumn } from "./SourceColumn.vue";
export { default as AddressColumn } from "./AddressColumn.vue";
export { default as CompanyColumn } from "./CompanyColumn.vue";
export { default as TypeDealColumn } from "./TypeDealColumn.vue";
