package crm_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	crm_models "github.com/pinks-agency/ecn/server/internal/crm-facade/models"
	staff_entity "github.com/pinks-agency/ecn/server/pkg/staff/entity"
)

// SaveDepartment is the resolver for the saveDepartment field.
func (r *mutationResolver) SaveDepartment(ctx context.Context, input crm_models.DepartmentInput) (bool, error) {
	_, err := r.StaffService.SaveDepartment(ctx, *input.ToEntity())
	if err != nil {
		return false, err
	}

	return true, nil
}

// DeleteDepartment is the resolver for the deleteDepartment field.
func (r *mutationResolver) DeleteDepartment(ctx context.Context, id string) (bool, error) {
	if err := r.StaffService.DeleteDepartment(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// Departments is the resolver for the departments field.
func (r *queryResolver) Departments(ctx context.Context, ids []string, start *int, limit *int, sort *crm_models.Sort, search *string) (*crm_models.DepartmentConnection, error) {
	departmentFilter := &staff_entity.DepartmentFilter{}
	departmentFilter.Keyword = search

	data, total, err := r.StaffService.SearchDepartments(ctx, start, limit, staff_entity.DepartmentSortDefault, departmentFilter)
	if err != nil {
		return nil, err
	}

	var nodes []*crm_models.Department
	for _, v := range data {
		nodes = append(nodes, new(crm_models.Department).FromEntity(v))
	}

	return &crm_models.DepartmentConnection{
		TotalCount: total,
		Nodes:      nodes,
		PageInfo:   &crm_models.PageInfo{},
	}, nil
}

// Department is the resolver for the department field.
func (r *queryResolver) Department(ctx context.Context, id string) (*crm_models.Department, error) {
	data, err := r.StaffService.GetDepartmentByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(crm_models.Department).FromEntity(data), nil
}
