package crm_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	crm_gateway "github.com/pinks-agency/ecn/server/internal/crm-facade/gateway"
	crm_models "github.com/pinks-agency/ecn/server/internal/crm-facade/models"
	content_entity "github.com/pinks-agency/ecn/server/pkg/content/entity"
	shared_entity "github.com/pinks-agency/ecn/server/pkg/shared/entity"
)

// SaveStory is the resolver for the saveStory field.
func (r *mutationResolver) SaveStory(ctx context.Context, input crm_models.StoryInput) (bool, error) {
	_, err := r.ContentService.SaveStory(ctx, *input.ToEntity())
	if err != nil {
		return false, err
	}

	return true, nil
}

// DeleteStory is the resolver for the deleteStory field.
func (r *mutationResolver) DeleteStory(ctx context.Context, id string) (bool, error) {
	if err := r.ContentService.DeleteStory(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// Stories is the resolver for the stories field.
func (r *queryResolver) Stories(ctx context.Context, ids []string, start *int, limit *int, sort *crm_models.Sort, search *string, filter *crm_models.StoryFilterInput) (*crm_models.StoryConnection, error) {
	storyFilter := &content_entity.StoryFilter{}
	if filter != nil {
		if filter.Category != nil {
			storyFilter.Category = (*content_entity.StoryCategory)(filter.Category)
		}

		if filter.PublicationStatus != nil {
			storyFilter.PublicationStatus = (*shared_entity.PublicationStatus)(filter.PublicationStatus)
		}

		storyFilter.Keyword = search
	}

	data, total, err := r.ContentService.SearchStories(ctx, start, limit, content_entity.StorySortDefault, storyFilter)
	if err != nil {
		return nil, err
	}

	var nodes []*crm_models.Story
	for _, v := range data {
		nodes = append(nodes, new(crm_models.Story).FromEntity(v))
	}

	return &crm_models.StoryConnection{
		TotalCount: total,
		Nodes:      nodes,
		PageInfo:   &crm_models.PageInfo{},
	}, nil
}

// Story is the resolver for the story field.
func (r *queryResolver) Story(ctx context.Context, id string) (*crm_models.Story, error) {
	data, err := r.ContentService.GetStoryByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(crm_models.Story).FromEntity(data), nil
}

// Cover is the resolver for the cover field.
func (r *storyResolver) Cover(ctx context.Context, obj *crm_models.Story) (*crm_models.Image, error) {
	if obj != nil && obj.CoverID != nil {
		data, err := r.ExchangeService.GetImageByID(ctx, *obj.CoverID)
		if err != nil {
			return nil, nil
		}

		return new(crm_models.Image).FromEntity(data), nil
	}

	return nil, nil
}

// Cover is the resolver for the cover field.
func (r *storyInputResolver) Cover(ctx context.Context, obj *crm_models.StoryInput, data *crm_models.ImageInput) error {
	if data != nil {
		if data.File != nil {
			result, err := r.ExchangeService.UploadImage(ctx, *data.ToEntity())
			if err != nil {
				return err
			}
			obj.CoverID = &result.ID
		} else if data.ID != "" {
			obj.CoverID = &data.ID
		}
	}
	return nil
}

// Story returns crm_gateway.StoryResolver implementation.
func (r *Resolver) Story() crm_gateway.StoryResolver { return &storyResolver{r} }

// StoryInput returns crm_gateway.StoryInputResolver implementation.
func (r *Resolver) StoryInput() crm_gateway.StoryInputResolver { return &storyInputResolver{r} }

type storyResolver struct{ *Resolver }
type storyInputResolver struct{ *Resolver }
