package crm_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	crm_models "github.com/pinks-agency/ecn/server/internal/crm-facade/models"
	content_entity "github.com/pinks-agency/ecn/server/pkg/content/entity"
)

// SaveVacancy is the resolver for the saveVacancy field.
func (r *mutationResolver) SaveVacancy(ctx context.Context, input crm_models.VacancyInput) (bool, error) {
	_, err := r.ContentService.SaveVacancy(ctx, *input.ToEntity())
	if err != nil {
		return false, err
	}

	return true, nil
}

// DeleteVacancy is the resolver for the deleteVacancy field.
func (r *mutationResolver) DeleteVacancy(ctx context.Context, id string) (bool, error) {
	if err := r.ContentService.DeleteVacancy(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// Vacancies is the resolver for the vacancies field.
func (r *queryResolver) Vacancies(ctx context.Context, ids []string, start *int, limit *int, sort *crm_models.Sort, search *string) (*crm_models.VacancyConnection, error) {
	data, total, err := r.ContentService.SearchVacancies(ctx, start, limit, content_entity.VacancySortDefault, &content_entity.VacancyFilter{
		Keyword: search,
	})
	if err != nil {
		return nil, err
	}

	var nodes []*crm_models.Vacancy
	for _, v := range data {
		nodes = append(nodes, new(crm_models.Vacancy).FromEntity(v))
	}

	return &crm_models.VacancyConnection{
		TotalCount: total,
		Nodes:      nodes,
		PageInfo:   &crm_models.PageInfo{},
	}, nil
}

// Vacancy is the resolver for the vacancy field.
func (r *queryResolver) Vacancy(ctx context.Context, id string) (*crm_models.Vacancy, error) {
	data, err := r.ContentService.GetVacancyByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(crm_models.Vacancy).FromEntity(data), nil
}
