package crm_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	crm_models "github.com/pinks-agency/ecn/server/internal/crm-facade/models"
	content_entity "github.com/pinks-agency/ecn/server/pkg/content/entity"
)

// ApproveVacancyRequest is the resolver for the approveVacancyRequest field.
func (r *mutationResolver) ApproveVacancyRequest(ctx context.Context, id string) (bool, error) {
	if err := r.ContentService.ApproveVacancyRequest(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// DeclineVacancyRequest is the resolver for the declineVacancyRequest field.
func (r *mutationResolver) DeclineVacancyRequest(ctx context.Context, id string) (bool, error) {
	if err := r.ContentService.DeclineVacancyRequest(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// VacancyRequests is the resolver for the vacancyRequests field.
func (r *queryResolver) VacancyRequests(ctx context.Context, ids []string, start *int, limit *int, sort *crm_models.Sort, search *string) (*crm_models.VacancyRequestConnection, error) {
	data, total, err := r.ContentService.SearchVacancyRequests(ctx, start, limit, content_entity.VacancyRequestSortDefault, &content_entity.VacancyRequestFilter{
		Keyword: search,
	})
	if err != nil {
		return nil, err
	}

	var nodes []*crm_models.VacancyRequest
	for _, v := range data {
		nodes = append(nodes, new(crm_models.VacancyRequest).FromEntity(v))
	}

	return &crm_models.VacancyRequestConnection{
		TotalCount: total,
		Nodes:      nodes,
		PageInfo:   &crm_models.PageInfo{},
	}, nil
}

// VacancyRequest is the resolver for the vacancyRequest field.
func (r *queryResolver) VacancyRequest(ctx context.Context, id string) (*crm_models.VacancyRequest, error) {
	data, err := r.ContentService.GetVacancyRequestByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(crm_models.VacancyRequest).FromEntity(data), nil
}
