query roles(
  $ids: [ID!]
  $start: Int
  $limit: Int
  $search: String
  $sort: Sort
) {
  roles(
    ids: $ids
    start: $start
    limit: $limit
    search: $search
    sort: $sort
  ) {
    totalCount
    nodes {
      id
      title
      permissions
    }
  }
}
