package public_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	public_gateway "github.com/pinks-agency/ecn/server/internal/public-facade/gateway"
	public_models "github.com/pinks-agency/ecn/server/internal/public-facade/models"
	estate_entity "github.com/pinks-agency/ecn/server/pkg/estate/entity"
)

// Logo is the resolver for the logo field.
func (r *developerResolver) Logo(ctx context.Context, obj *public_models.Developer) (*public_models.Image, error) {
	if obj != nil && obj.LogoID != nil {
		data, err := r.ExchangeService.GetImageByID(ctx, *obj.LogoID)
		if err != nil {
			return nil, nil
		}

		return new(public_models.Image).FromEntity(data), nil
	}

	return nil, nil
}

// Developers is the resolver for the developers field.
func (r *queryResolver) Developers(ctx context.Context, ids []string, start *int, limit *int, sort *public_models.Sort, search *string) (*public_models.DeveloperConnection, error) {
	developerFilter := &estate_entity.DeveloperFilter{
		Keyword: search,
	}

	data, total, err := r.EstateService.SearchDevelopers(ctx, start, limit, estate_entity.DeveloperSortDefault, developerFilter)
	if err != nil {
		return nil, err
	}

	var nodes []*public_models.Developer
	for _, v := range data {
		nodes = append(nodes, new(public_models.Developer).FromEntity(v))
	}

	return &public_models.DeveloperConnection{
		TotalCount: total,
		Nodes:      nodes,
		PageInfo:   &public_models.PageInfo{},
	}, nil
}

// Developer is the resolver for the developer field.
func (r *queryResolver) Developer(ctx context.Context, id string) (*public_models.Developer, error) {
	data, err := r.EstateService.GetDeveloperByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(public_models.Developer).FromEntity(data), nil
}

// Developer returns public_gateway.DeveloperResolver implementation.
func (r *Resolver) Developer() public_gateway.DeveloperResolver { return &developerResolver{r} }

type developerResolver struct{ *Resolver }
