package public_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	public_gateway "github.com/pinks-agency/ecn/server/internal/public-facade/gateway"
	public_models "github.com/pinks-agency/ecn/server/internal/public-facade/models"
)

// Reviews is the resolver for the reviews field.
func (r *queryResolver) Reviews(ctx context.Context, ids []string, start *int, limit *int, sort *public_models.Sort, search *string, filter *public_models.ReviewsFilterInput) (*public_models.ReviewConnection, error) {
	panic(fmt.Errorf("not implemented: Reviews - reviews"))
}

// Review is the resolver for the review field.
func (r *queryResolver) Review(ctx context.Context, id string) (*public_models.Review, error) {
	panic(fmt.Errorf("not implemented: Review - review"))
}

// Employee is the resolver for the employee field.
func (r *reviewResolver) Employee(ctx context.Context, obj *public_models.Review) (*public_models.Employee, error) {
	panic(fmt.Errorf("not implemented: Employee - employee"))
}

// Review returns public_gateway.ReviewResolver implementation.
func (r *Resolver) Review() public_gateway.ReviewResolver { return &reviewResolver{r} }

type reviewResolver struct{ *Resolver }
