package public_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	public_models "github.com/pinks-agency/ecn/server/internal/public-facade/models"
)

// CreateVacancyRequest is the resolver for the createVacancyRequest field.
func (r *mutationResolver) CreateVacancyRequest(ctx context.Context, input public_models.VacancyRequestInput) (bool, error) {
	panic(fmt.Errorf("not implemented: CreateVacancyRequest - createVacancyRequest"))
}
