package public_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	public_gateway "github.com/pinks-agency/ecn/server/internal/public-facade/gateway"
	public_models "github.com/pinks-agency/ecn/server/internal/public-facade/models"
	estate_entity "github.com/pinks-agency/ecn/server/pkg/estate/entity"
	shared_entity "github.com/pinks-agency/ecn/server/pkg/shared/entity"
	"github.com/pinks-agency/ecn/server/utils"
)

// Villages is the resolver for the villages field.
func (r *queryResolver) Villages(ctx context.Context, ids []string, start *int, limit *int, sort *public_models.Sort, search *string) (*public_models.VillageConnection, error) {
	villageFilter := &estate_entity.VillageFilter{
		Keyword:           search,
		PublicationStatus: utils.Pointer(shared_entity.PublicationStatusPublished),
	}

	data, total, err := r.EstateService.SearchVillages(ctx, start, limit, estate_entity.VillageSortDefault, villageFilter)
	if err != nil {
		return nil, err
	}

	var nodes []*public_models.Village
	for _, v := range data {
		nodes = append(nodes, new(public_models.Village).FromEntity(v))
	}

	return &public_models.VillageConnection{
		TotalCount: total,
		Nodes:      nodes,
		PageInfo:   &public_models.PageInfo{},
	}, nil
}

// Village is the resolver for the village field.
func (r *queryResolver) Village(ctx context.Context, id string) (*public_models.Village, error) {
	data, err := r.EstateService.GetVillageByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(public_models.Village).FromEntity(data), nil
}

// Developer is the resolver for the developer field.
func (r *villageResolver) Developer(ctx context.Context, obj *public_models.Village) (*public_models.Developer, error) {
	if obj.DeveloperID != nil {
		data, err := r.EstateService.GetDeveloperByID(ctx, *obj.DeveloperID)
		if err != nil {
			return nil, err
		}

		return new(public_models.Developer).FromEntity(data), nil
	}

	return nil, nil
}

// Images is the resolver for the images field.
func (r *villageResolver) Images(ctx context.Context, obj *public_models.Village) ([]*public_models.Image, error) {
	result := make([]*public_models.Image, 0, len(obj.ImageIDs))

	for _, v := range obj.ImageIDs {
		data, err := r.ExchangeService.GetImageByID(ctx, v)
		if err != nil {
			return nil, nil
		}

		result = append(result, new(public_models.Image).FromEntity(data))
	}

	return result, nil
}

// Documents is the resolver for the documents field.
func (r *villageResolver) Documents(ctx context.Context, obj *public_models.Village) ([]*public_models.Document, error) {
	result := make([]*public_models.Document, 0, len(obj.DocumentIDs))

	for _, v := range obj.DocumentIDs {
		data, err := r.ExchangeService.GetDocumentByID(ctx, v)
		if err != nil {
			return nil, nil
		}

		result = append(result, new(public_models.Document).FromEntity(data))
	}

	return result, nil
}

// ProjectDeclarations is the resolver for the projectDeclarations field.
func (r *villageResolver) ProjectDeclarations(ctx context.Context, obj *public_models.Village) ([]*public_models.Document, error) {
	result := make([]*public_models.Document, 0, len(obj.ProjectDeclarationIDs))

	for _, v := range obj.ProjectDeclarationIDs {
		data, err := r.ExchangeService.GetDocumentByID(ctx, v)
		if err != nil {
			return nil, nil
		}

		result = append(result, new(public_models.Document).FromEntity(data))
	}

	return result, nil
}

// Village returns public_gateway.VillageResolver implementation.
func (r *Resolver) Village() public_gateway.VillageResolver { return &villageResolver{r} }

type villageResolver struct{ *Resolver }
