query articleGroups(
  $start: Int
  $limit: Int
  $search: String
  $sort: Sort
) {
  articleGroups(
    start: $start
    limit: $limit
    search: $search
    sort: $sort
  ) {
    totalCount
    nodes {
      id
      title
      createdAt
      updatedAt
    }
  }
}
