/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
