package errs

import (
	"fmt"

	shared_entity "github.com/pinks-agency/ecn/server/pkg/shared/entity"
)

type Error struct {
	Code string
}

func (e *Error) Error() string {
	return fmt.Sprintf("code: %s", e.Code)
}

func GetCodeFromError(err error) string {
	customError, _ := err.(*Error)
	return customError.Code
}

func New(code string) *Error {
	return &Error{
		Code: code,
	}
}

// Staff Errors
var (
	ErrDecodeEmployeeLogin                             = New(string(shared_entity.StatusCodeStaffLoginDecodeError))
	ErrInvalidPassword                                 = New(string(shared_entity.StatusCodeStaffLoginInvalidPassword))
	ErrCreateToken                                     = New(string(shared_entity.StatusCodeStaffLoginCreateTokenError))
	ErrInsertOneEmployeeCreate                         = New(string(shared_entity.StatusCodeStaffEmployeeCreateInsertOneError))
	ErrDecodeEmployeeCreate                            = New(string(shared_entity.StatusCodeStaffEmployeeCreateDecodeError))
	ErrDecodeEmployeeUpdate                            = New(string(shared_entity.StatusCodeStaffEmployeeUpdateDecodeError))
	ErrConvertIDEmployeeUpdate                         = New(string(shared_entity.StatusCodeStaffEmployeeUpdateIDFromHexError))
	ErrConvertIDEmployeeDelete                         = New(string(shared_entity.StatusCodeStaffEmployeeDeleteIDFromHexError))
	ErrConvertIDBulkActivateEmployee                   = New(string(shared_entity.StatusCodeStaffEmployeeBulkActivateIDFromHexError))
	ErrUpdateManyBulkActivateEmployee                  = New(string(shared_entity.StatusCodeStaffEmployeeBulkActivateUpdateManyError))
	ErrConvertIDBulkPublishEmployee                    = New(string(shared_entity.StatusCodeStaffEmployeeBulkPublishIDFromHexError))
	ErrUpdateManyBulkPublishEmployee                   = New(string(shared_entity.StatusCodeStaffEmployeeBulkPublishUpdateManyError))
	ErrConvertIDBulkAssignRoleEmployee                 = New(string(shared_entity.StatusCodeStaffEmployeeBulkAssignRoleEntityIDFromHexError))
	ErrConvertRoleIDBulkAssignRoleEmployee             = New(string(shared_entity.StatusCodeStaffEmployeeBulkAssignRoleRoleIDFromHexError))
	ErrUpdateManyBulkAssignRoleEmployee                = New(string(shared_entity.StatusCodeStaffEmployeeBulkAssignRoleUpdateManyError))
	ErrConvertIDBulkAssignDepartmentEmployee           = New(string(shared_entity.StatusCodeStaffEmployeeBulkAssignDepartmentEntityIDFromHexError))
	ErrConvertDepartmentIDBulkAssignDepartmentEmployee = New(string(shared_entity.StatusCodeStaffEmployeeBulkAssignDepartmentDepartmentIDFromHexError))
	ErrConvertGroupIDBulkAssignDepartmentEmployee      = New(string(shared_entity.StatusCodeStaffEmployeeBulkAssignDepartmentGroupIDFromHexError))
	ErrUpdateManyBulkAssignDepartmentEmployee          = New(string(shared_entity.StatusCodeStaffEmployeeBulkAssignDepartmentUpdateManyError))
	ErrUpdateManyBulkDeleteEmployee                    = New(string(shared_entity.StatusCodeStaffEmployeeBulkDeleteUpdateManyError))
	ErrConvertIDBulkeDeleteEmployee                    = New(string(shared_entity.StatusCodeStaffEmployeeBulkDeleteIDFromHexError))
	ErrInsertOnePositionCreate                         = New(string(shared_entity.StatusCodeStaffPositionCreateInsertOneError))
	ErrDecodePositionCreate                            = New(string(shared_entity.StatusCodeStaffPositionCreateDecodeError))
	ErrConvertIDPositionUpdate                         = New(string(shared_entity.StatusCodeStaffPositionUpdateIDFromHexError))
	ErrDecodePositionUpdate                            = New(string(shared_entity.StatusCodeStaffEmployeeUpdateDecodeError))
	ErrConvertIDPositionDelete                         = New(string(shared_entity.StatusCodeStaffPositionDeleteIDFromHexError))
	ErrDeleteOnePositionDelete                         = New(string(shared_entity.StatusCodeStaffPositionDeleteOneError))
	ErrConvertIDPositionBulkDelete                     = New(string(shared_entity.StatusCodeStaffPositionBulkDeleteIDFromHexError))
	ErrDeleteManyPositionBulkDelete                    = New(string(shared_entity.StatusCodeStaffPositionBulkDeleteDeleteManyError))
	ErrInsertOneRoleCreate                             = New(string(shared_entity.StatusCodeStaffRoleCreateInsertOneError))
	ErrDecodeRoleCreate                                = New(string(shared_entity.StatusCodeStaffRoleCreateDecodeError))
	ErrConvertIDRoleUpdate                             = New(string(shared_entity.StatusCodeStaffRoleUpdateIDFromHexError))
	ErrDecodeRoleUpdate                                = New(string(shared_entity.StatusCodeStaffRoleUpdateDecodeError))
	ErrConvertIDRoleDelete                             = New(string(shared_entity.StatusCodeStaffRoleDeleteIDFromHexError))
	ErrDeleteOneRoleDelete                             = New(string(shared_entity.StatusCodeStaffRoleDeleteDeleteOneError))
	ErrConvertIDRoleBulkDelete                         = New(string(shared_entity.StatusCodeStaffRoleBulkDeleTeIDFromHexError))
	ErrDeleteManyRoleBulkDelete                        = New(string(shared_entity.StatusCodeStaffRoleBulkDeleteDeleteManyError))
	ErrInsertOneDepartmentCreate                       = New(string(shared_entity.StatusCodeStaffDepartmentCreateInsertOneError))
	ErrInsertManyDepartmentGroupCreate                 = New(string(shared_entity.StatusCodeStaffDepartmentGroupCreateInsertManyError))
	ErrDecodeDepartmentCreate                          = New(string(shared_entity.StatusCodeStaffDepartmentCreateDecodeError))
	ErrConvertIDDepartmentUpdate                       = New(string(shared_entity.StatusCodeStaffDepartmentUpdateIDFromHexError))
	ErrDecodeOldDepartmentUpdate                       = New(string(shared_entity.StatusCodeStaffDepartmentUpdateDecodeOldError))
	ErrFindGroupDepartmentUpdate                       = New(string(shared_entity.StatusCodeStaffDepartmentUpdateFindGroupError))
	ErrDecodeGroupDepartmentUpdate                     = New(string(shared_entity.StatusCodeStaffDepartmentUpdateDecodeGroupError))
	ErrDecodeDepartmentUpdate                          = New(string(shared_entity.StatusCodeStaffDepartmentUpdateDecodeError))
	ErrInsertOneGroupDepartmentUpdate                  = New(string(shared_entity.StatusCodeStaffDepartmentUpdateInsertOneGroupError))
	ErrUpdateByIDGroupDepartmentUpdate                 = New(string(shared_entity.StatusCodeStaffDepartmentUpdateUpdateByIDGroupError))
	ErrDeleteOneGroupDepartmentUpdate                  = New(string(shared_entity.StatusCodeStaffDepartmentUpdateDeleteOneGroupError))
	ErrConvertIDDepartmentDelete                       = New(string(shared_entity.StatusCodeStaffDepartmentDeleteIDFromHexError))
	ErrDeleteOneDepartmentDelete                       = New(string(shared_entity.StatusCodeStaffDepartmentDeleteDeleteOneError))
	ErrDeleteManyGroupDepartmentDelete                 = New(string(shared_entity.StatusCodeStaffDepartmentDeleteDeleteManyGroupError))
	ErrConvertIDDepartmentBulkDelete                   = New(string(shared_entity.StatusCodeStaffDepartmentBulkDeleteIDFromHexError))
	ErrDeleteManyDepartmentBulkDelete                  = New(string(shared_entity.StatusCodeStaffDepartmentBulkDeleteDeleteManyError))
	ErrDeleteManyGroupDepartmentBulkDelete             = New(string(shared_entity.StatusCodeStaffDepartmentBulkDeleteDeleteManyGroupError))
)

// Estate Errors
var (
	ErrInsertOneComplexHouseCreate        = New(string(shared_entity.StatusCodeEstateComplexHouseCreateInsertOneError))
	ErrDecodeComplexHouseCreate           = New(string(shared_entity.StatusCodeEstateComplexHouseCreateDecodeError))
	ErrConvertIDComplexHouseUpdate        = New(string(shared_entity.StatusCodeEstateComplexHouseUpdateIDFromHexError))
	ErrDecodeComplexHouseUpdate           = New(string(shared_entity.StatusCodeEstateComplexHouseUpdateDecodeError))
	ErrConvertIDComplexHouseDelete        = New(string(shared_entity.StatusCodeEstateComplexHouseDeleteIDFromHexError))
	ErrDocComplexHouseDelete              = New(string(shared_entity.StatusCodeEstateComplexHouseDocError))
	ErrConvertIDComplexHouseBulkDelete    = New(string(shared_entity.StatusCodeEstateComplexHouseBulkDeleteIDFromHexError))
	ErrUpdateManyComplexHouseBulkDelete   = New(string(shared_entity.StatusCodeEstateComplexHouseBulkDeleteUpdateManyError))
	ErrInsertOneComplexCreate             = New(string(shared_entity.StatusCodeEstateComplexCreateInsertOneError))
	ErrDecodeComplexCreate                = New(string(shared_entity.StatusCodeEstateComplexCreateDecodeError))
	ErrConvertIDComplexUpdate             = New(string(shared_entity.StatusCodeEstateComplexUpdateIDFromHexError))
	ErrDecodeComplexUpdate                = New(string(shared_entity.StatusCodeEstateComplexUpdateDecodeError))
	ErrConvertIDComplexDelete             = New(string(shared_entity.StatusCodeEstateComplexDeleteIDFromHexError))
	ErrDocComplexDelete                   = New(string(shared_entity.StatusCodeEstateComplexDeleteDocError))
	ErrConvertIDComplexBulkDelete         = New(string(shared_entity.StatusCodeEstateComplexBulkDeleteIDFromHexError))
	ErrUpdateManyComplexBulkDelete        = New(string(shared_entity.StatusCodeEstateComplexBulkDeleteUpdateManyError))
	ErrInsertOneDeveloperCreate           = New(string(shared_entity.StatusCodeEstateDeveloperCreateInsertOneError))
	ErrDecodeDeveloperCreate              = New(string(shared_entity.StatusCodeEstateDeveloperCreateDecodeError))
	ErrConvertIDDeveloperUpdate           = New(string(shared_entity.StatusCodeEstateDeveloperUpdateIDFromHexError))
	ErrDecodeDeveloperUpdate              = New(string(shared_entity.StatusCodeEstateDeveloperUpdateDecodeError))
	ErrConvertIDDeveloperDelete           = New(string(shared_entity.StatusCodeEstateDeveloperDeleteIDFromHexError))
	ErrDocDeveloperDelete                 = New(string(shared_entity.StatusCodeEstateDeveloperDeleteDocError))
	ErrConvertIDDeveloperBulkDelete       = New(string(shared_entity.StatusCodeEsateDeveloperBulkDeleteIDFromHexError))
	ErrUpdateManyDeveloperBulkDelete      = New(string(shared_entity.StatusCodeEstateDeveloperBulkDeleteUpdateManyError))
	ErrInsertOnePropertyCreate            = New(string(shared_entity.StatusCodeEstatePropertyCreateInsertOneError))
	ErrDecodePropertyCreate               = New(string(shared_entity.StatusCodeEstatePropertyCreateDecodeError))
	ErrConvertIDPropertyUpdate            = New(string(shared_entity.StatusCodeEstatePropertyUpdateIDFromHexError))
	ErrDecodePropertyUpdate               = New(string(shared_entity.StatusCodeEstatePropertyUpdateDecodeError))
	ErrConvertIDPropertyDelete            = New(string(shared_entity.StatusCodeEstatePropertyDeleteIDFromHexError))
	ErrDocPropertyDelete                  = New(string(shared_entity.StatusCodeEstatePropertyDeleteDocError))
	ErrConvertIDPropertyChangeStatus      = New(string(shared_entity.StatusCodeEstatePropertyChangeStatusIDFromHexError))
	ErrDocPropertyChangeStatus            = New(string(shared_entity.StatusCodeEstatePropertyChangeStatusDocError))
	ErrConvertIDPropertyRefresh           = New(string(shared_entity.StatusCodeEstatePropertyRefreshIDFromHexError))
	ErrDocPropertyRefresh                 = New(string(shared_entity.StatusCodeEstatePropertyRefreshDocError))
	ErrConvertIDPropertyBulkDelete        = New(string(shared_entity.StatusCodeEstatePropertyBulkDeleteIDFromHexError))
	ErrUpdateManyPropertyBulkDelete       = New(string(shared_entity.StatusCodeEstatePropertyBulkDeleteUpdateManyError))
	ErrConvertIDPropertyBulkChangeStatus  = New(string(shared_entity.StatusCodeEstatePropertyBulkChangeStatusIDFromHexError))
	ErrUpdateManyPropertyBulkChangeStatus = New(string(shared_entity.StatusCodeEstatePropertyBulkChangeStatusUpdateManyError))
	ErrConvertIDPropertyBulkRefresh       = New(string(shared_entity.StatusCodeEstatePropertyBulkRefreshIDFromHexError))
	ErrUpdateManyPropertyBulkRefresh      = New(string(shared_entity.StatusCodeEstatePropertyBulkRefreshUpdateManyError))
	ErrInsertOneVillageCreate             = New(string(shared_entity.StatusCodeEstateVillageCreateInsertOneError))
	ErrDecodeVillageCreate                = New(string(shared_entity.StatusCodeEstateVillageCreateDecodeError))
	ErrConvertIDVillageUpdate             = New(string(shared_entity.StatusCodeEstateVillageUpdateIDFromHexError))
	ErrDecodeVillageUpdate                = New(string(shared_entity.StatusCodeEstateVillageUpdateDecodeError))
	ErrConvertIDVillageDelete             = New(string(shared_entity.StatusCodeEstateVillageDeleteIDFromHexError))
	ErrDocVillageDelete                   = New(string(shared_entity.StatusCodeEstateVillageDeleteDocError))
	ErrConvertIDVillageBulkDelete         = New(string(shared_entity.StatusCodeEstateVillageBulkDeleteIDFromHexError))
	ErrUpdateManyVillageBulkDelete        = New(string(shared_entity.StatusCodeEstateVillageBulkDeleteUpdateManyError))
)

// Sales Errors
var (
	ErrInsertOneContactCreate                    = New(string(shared_entity.StatusCodeSalesContactCreateInsertOneError))
	ErrDecodeContactCreate                       = New(string(shared_entity.StatusCodeSalesContactCreateDecodeError))
	ErrConvertIDConctactUpdate                   = New(string(shared_entity.StatusCodeSalesContactUpdateIDFromHexError))
	ErrDecodeContactUpdate                       = New(string(shared_entity.StatusCodeSalesContactUpdateDecodeError))
	ErrConvertIDContactDelete                    = New(string(shared_entity.StatusCodeSalesContactDeleteIDFromHexError))
	ErrDocContactDelete                          = New(string(shared_entity.StatusCodeSalesContactDeleteDocError))
	ErrConvertIDContactBulkDelete                = New(string(shared_entity.StatusCodeSalesContactBulkDeleteIDFromHexError))
	ErrUpdateManyContactBulkDelete               = New(string(shared_entity.StatusCodeSalesContactBulkDeleteUpdateManyError))
	ErrInsertOneDealCreate                       = New(string(shared_entity.StatusCodeSalesDealCreateInsertOneError))
	ErrDecodeDealCreate                          = New(string(shared_entity.StatusCodeSalesDealCreateDecodeError))
	ErrConvertIDDealUpdate                       = New(string(shared_entity.StatusCodeSalesDealUpdateIDFromHexError))
	ErrDecodeDealUpdate                          = New(string(shared_entity.StatusCodeSalesDealUpdateDecodeError))
	ErrConvertIDDealDelete                       = New(string(shared_entity.StatusCodeSalesDealDeleteIDFromHexError))
	ErrDocDealDelete                             = New(string(shared_entity.StatusCodeSalesDealDeleteDocError))
	ErrConvertIDDealChangeStage                  = New(string(shared_entity.StatusCodeSalesDealChangeStageIDFromHexError))
	ErrUpdateOneDealChangeStage                  = New(string(shared_entity.StatusCodeSalesDealChangeStageUpdateOneError))
	ErrConvertIDDealBulkDelete                   = New(string(shared_entity.StatusCodeSalesDealBulkDeleteIDFromHexError))
	ErrUpdateManyDealBulKDelete                  = New(string(shared_entity.StatusCodeSalesDealBulkDeleteUpdateManyError))
	ErrConvertIDDealBulkChangeStage              = New(string(shared_entity.StatusCodeSalesDealBulkChangeStageIDFromHexError))
	ErrUpdateManyDealBulkChangeStage             = New(string(shared_entity.StatusCodeSalesDealBulkChangeStageUpdateManyError))
	ErrInsertOneLeadCreate                       = New(string(shared_entity.StatusCodeSalesLeadCreateInsertOneError))
	ErrDecodeLeadCreate                          = New(string(shared_entity.StatusCodeSalesLeadCreateDecodeError))
	ErrConvertIDLeadUpdate                       = New(string(shared_entity.StatusCodeSalesLeadUpdateIDFromHexError))
	ErrDecodeLeadUpdate                          = New(string(shared_entity.StatusCodeSalesLeadUpdateDecodeError))
	ErrConvertIDLeadDelete                       = New(string(shared_entity.StatusCodeSalesLeadDeleteIDFromHexError))
	ErrDocLeadDelete                             = New(string(shared_entity.StatusCodeSalesLeadDeleteDocError))
	ErrConvertIDLeadChangeStatus                 = New(string(shared_entity.StatusCodeSalesLeadChangeStatusIDFromHexError))
	ErrUpdateOneLeadChangeStatus                 = New(string(shared_entity.StatusCodeSalesLeadChangeStatusUpdateOneError))
	ErrConvertIDLeadBulkDelete                   = New(string(shared_entity.StatusCodeSalesLeadBulkDeleteIDFromHexError))
	ErrUpdateManyLeadBulkDelete                  = New(string(shared_entity.StatusCodeSalesLeadBulkDeleteUpdateManyError))
	ErrConvertIDLeadBulkChangeStatus             = New(string(shared_entity.StatusCodeSalesLeadBulkChangeStatusIDFromHexError))
	ErrUpdateManyLeadBulkChangeStatus            = New(string(shared_entity.StatusCodeSalesLeadBulkChangeStatusUpdateManyError))
	ErrInsertOneMeetCreate                       = New(string(shared_entity.StatusCodeSalesMeetInsertOneError))
	ErrDecodeMeetCreate                          = New(string(shared_entity.StatusCodeSalesMeetDecodeError))
	ErrConvertIDMeetUpdate                       = New(string(shared_entity.StatusCodeSalesMeetUpdateIDFromHexError))
	ErrDecodeMeetUpdate                          = New(string(shared_entity.StatusCodeSalesMeetUpdateDecodeError))
	ErrConvertIDMeetDelete                       = New(string(shared_entity.StatusCodeSalesMeetDeleteIDFromHexError))
	ErrDocMeetDelete                             = New(string(shared_entity.StatusCodeSalesMeetDeleteDocError))
	ErrConvertIDMeetChangeStatus                 = New(string(shared_entity.StatusCodeSalesMeetChangeStatusIDFromHexError))
	ErrUpdateOneMeetChangeStatus                 = New(string(shared_entity.StatusCodeSalesMeetChangeStatusUpdateOneError))
	ErrConvertIDMeetBulkDelete                   = New(string(shared_entity.StatusCodeSalesMeetBulkDeleteIDFromHexError))
	ErrUpdateManyMeetBulkDelete                  = New(string(shared_entity.StatusCodeSalesMeetBulkDeleteUpdateManyError))
	ErrConvertIDMeetBulkChangeStatus             = New(string(shared_entity.StatusCodeSalesMeetBulkChangeStatusIDFromHexError))
	ErrUpdateManyMeetBulkChangeStatus            = New(string(shared_entity.StatusCodeSalesMeetBulkChangeStatusUpdateManyError))
	ErrInsertOneTaskCreate                       = New(string(shared_entity.StatusCodeSalesTaskCreateInsertOneError))
	ErrDecodeTaskCreate                          = New(string(shared_entity.StatusCodeSalesTaskCreateDecodeError))
	ErrConvertIDTaskUpdate                       = New(string(shared_entity.StatusCodeSalesTaskUpdateIDFromHexError))
	ErrDecodeTaskUpdate                          = New(string(shared_entity.StatusCodeSalesTaskUpdateDecodeError))
	ErrConvertIDTaskDelete                       = New(string(shared_entity.StatusCodeSalesTaskDeleteIDFromHexError))
	ErrDocTaskDelete                             = New(string(shared_entity.StatusCodeSalesTaskDeleteDocError))
	ErrConvertIDTaskComplete                     = New(string(shared_entity.StatusCodeSalesTaskCompleteIDFromHexError))
	ErrUpdateOneTaskComplete                     = New(string(shared_entity.StatusCodeSalesTaskCompleteUpdateOneError))
	ErrConvertIDTaskBulkDelete                   = New(string(shared_entity.StatusCodeSalesTaskBulkDeleteIDFromHexError))
	ErrUpdateManyTaskBulkDelete                  = New(string(shared_entity.StatusCodeSalesTaskBulkDeleteUpdateManyError))
	ErrConvertIDTaskBulkComplete                 = New(string(shared_entity.StatusCodeSalesTaskBulkCompleteIDFromHexError))
	ErrUpdateManyTaskBulkComplete                = New(string(shared_entity.StatusCodeSalesTaskBulkCompleteUpdateManyError))
	ErrInsertOneMortgageRequestCreate            = New(string(shared_entity.StatusCodeSalesMortgageRequestCreateInsertOneError))
	ErrDecodeMortgageRequestCreate               = New(string(shared_entity.StatusCodeSalesMortgageRequestCreateDecodeError))
	ErrConvertIDMortgageRequestUpdate            = New(string(shared_entity.StatusCodeSalesMortgageRequestUpdateIDFromHexError))
	ErrDecodeMortgageRequestUpdate               = New(string(shared_entity.StatusCodeSalesMortgageRequestUpdateDecodeError))
	ErrConvertIDMortgageRequestDelete            = New(string(shared_entity.StatusCodeSalesMortgageRequestDeleteIDFromHexError))
	ErrDocMortgageRequestDelete                  = New(string(shared_entity.StatusCodeSalesMortgageRequestDeleteDocError))
	ErrConvertIDMortgageRequestChangeStatus      = New(string(shared_entity.StatusCodeSalesMortgageRequestChangeStatusIDFromHexError))
	ErrUpdateOneMortgageRequestChangeStatus      = New(string(shared_entity.StatusCodeSalesMortgageRequestChangeStatusUpdateOneError))
	ErrConvertIDMortgageRequestBulkDelete        = New(string(shared_entity.StatusCodeSalesMortgageRequestBulkDeleteIDFromHexError))
	ErrUpdateManyMortgageRequestBulkDelete       = New(string(shared_entity.StatusCodeSalesMortgageRequestBulkDeleteUpdateManyError))
	ErrConvertIDMortgageRequestBulkChangeStatus  = New(string(shared_entity.StatusCodeSalesMortgageRequestBulkChangeStatusIDFromHexError))
	ErrUpdateManyMortgageRequestBulkChangeStatus = New(string(shared_entity.StatusCodeSalesMortgageRequestBulkChangeStatusUpdateManyError))
)
